### ISSUE TITLE
Fix readme

### ISSUE THREAD

**Issue by gourcetools** [jb55/nostril#21]
I see the readme is a .txt file, i wonder if it should be a .md for readability on github.com

**Comment by jb55** [comment]
It's the manpage scdoc source so I don't have to tinker with it. Maybe if there was a scdoc to markdown tool

**Comment by gourcetools** [comment]
oh i see. my bad

**Comment by gourcetools** [comment]
I see you fixed it in https://github.com/jb55/nostril/commit/914e1fd11138f32bd9dbd241822bedfb68d8a381 . thanks
