### ISSUE TITLE
How can I report posts?

### ISSUE THREAD

**Issue by scuba323** [jb55/nostril#31]
When I am trying to report a post, I am not sure how to add the
 ````,"spam"```` at the end of the person's pubkey. 

Is this possible?

**Comment by jb55** [comment]
On Fri, Jul 07, 2023 at 03:18:21PM -0700, Stephen Vanderwarker wrote:
>When I am trying to report a post, I am not sure how to add the
> ````,"spam"```` at the end of the person's pubkey.
>
>Is this possible?

I need more context, I don't know what you're trying to do. Are you
trying to create report events?

**Comment by scuba323** [comment]
I would like to create 1984 (report) for spam but I can't seem to add the spam after the persons public key, or event.

**Comment by scuba323** [comment]
Sorry for stale bump, but I meant how do you add a second value in the same key.

**Comment by jb55** [comment]
On Sun, Sep 17, 2023 at 05:30:15AM -0700, Stephen Vanderwarker wrote:
>Sorry for stale bump, but I meant how do you add a second value in the same key.

ok I see what you mean, nostril can only add single key/value style tags
right now. if you want to do something more custom you can just pass the
entire tag array with --tags '[]'

**Comment by scuba323** [comment]
Awesome! Thanks sorry didn't make it clear at first 😂🫂
