### ISSUE TITLE
is it possible to add tags with multiple values?

### ISSUE THREAD

**Issue by melvincarvalho** [jb55/nostril#34]
I dont really think tags with multiple values are a great idea, but they are needed in some things such as replies

Is there a way to add tags with multiple values with nostril?

**Comment by jb55** [comment]
not at the moment, but you can pass a --tags argument which uses a json value verbatim for the entire tags array.

Would be happy if someone added this though. Not sure what the best interface is.

**Comment by jb55** [comment]
Fixed in 

- #36
