### ISSUE TITLE
Tag with a value of ["-"]

### ISSUE THREAD

**Issue by melvincarvalho** [jb55/nostril#35]
Is there a way to add a Tag with a value of ["-"]

Wasnt clear if there was some clever way to do this from the command line, bearing in mind that "-" is also a switch

**Comment by jb55** [comment]
I guess `nostril --tag "-" ""` kind of works, maybe we need a `--tag1` or `--tagn 3 a b c`

**Comment by jb55** [comment]
Fixed by: 

- #36
